covidlist = ["World","USA","India","France","Germany","Brazil","Japan","S. Korea","Italy","UK","Russia","Turkey","Spain","Vietnam","Australia","Taiwan","Argentina","Netherlands","Iran","Mexico","Indonesia","Poland","Colombia","Austria","Greece","Portugal","Ukraine","Chile","Malaysia","Israel","Belgium","DPRK","Thailand","Canada","Czechia","Peru","Switzerland","Philippines","South Africa","Romania","Denmark","Hong Kong","Sweden","Serbia","Iraq","Singapore","New Zealand","Hungary","Bangladesh","Slovakia","Georgia","Jordan","Ireland","Pakistan","Norway","Finland","Kazakhstan","Slovenia","Lithuania","Bulgaria","Morocco","Croatia","Guatemala","Lebanon","Costa Rica","Bolivia","Tunisia","Cuba","UAE","Ecuador","Uruguay","Panama","Mongolia","Nepal","Belarus","Latvia","Saudi Arabia","Azerbaijan","Paraguay","Bahrain","Sri Lanka","Kuwait","Dominican Republic","Cyprus","Myanmar","Palestine","Moldova","Estonia","Venezuela","Egypt","Libya","Qatar","China","Ethiopia","Réunion","Honduras","Armenia","Bosnia and Herzegovina","Oman","North Macedonia","Zambia","Kenya","Albania","Botswana","Luxembourg","Montenegro","Brunei","Algeria","Nigeria","Zimbabwe","Uzbekistan","Mozambique","Martinique","Laos","Afghanistan","Iceland","Kyrgyzstan","Guadeloupe","El Salvador","Trinidad and Tobago","Maldives","Ghana","Namibia","Uganda","Jamaica","Cambodia","Rwanda","Cameroon","Malta","Barbados","Angola","Channel Islands","French Guiana","DRC","Senegal","Malawi","Ivory Coast","Suriname","New Caledonia","French Polynesia","Eswatini","Guyana","Belize","Fiji","Madagascar","Sudan","Mauritania","Cabo Verde","Bhutan","Syria","Burundi","Seychelles","Gabon","Andorra","Papua New Guinea","Curaçao","Aruba","Tanzania","Mauritius","Mayotte","Togo","Guinea","Isle of Man","Bahamas","Lesotho","Faeroe Islands","Haiti","Mali","Cayman Islands","Saint Lucia","Benin","Somalia","Micronesia","Congo","Solomon Islands","San Marino","Timor-Leste","Burkina Faso","Liechtenstein","Gibraltar","Grenada","Bermuda","Nicaragua","South Sudan","Tajikistan","Equatorial Guinea","Tonga","Samoa","Monaco","Marshall Islands","Dominica","Djibouti","CAR","Gambia","Saint Martin","Vanuatu","Greenland","Yemen","Caribbean Netherlands","Sint Maarten","Eritrea","Niger","St. Vincent Grenadines","Guinea-Bissau","Antigua and Barbuda","Comoros","Liberia","Sierra Leone","Chad","British Virgin Islands","Cook Islands","Saint Kitts and Nevis","Turks and Caicos","Sao Tome and Principe","Palau","St. Barth","Nauru","Kiribati","Anguilla","Macao","Saint Pierre Miquelon","Wallis and Futuna","Tuvalu","Saint Helena","Falkland Islands","Montserrat","Niue","Diamond Princess","Vatican City","Western Sahara","MS Zaandam","Tokelau",""]

maplist = [ "Fiji", "Tanzania", "W. Sahara", "Canada", "United States of America", "Kazakhstan", "Uzbekistan", "Papua New Guinea", "Indonesia", "Argentina", "Chile", "Dem. Rep. Congo", "Somalia", "Kenya", "Sudan", "Chad", "Haiti", "Dominican Rep.", "Russia", "Bahamas", "Falkland Is.", "Norway", "Greenland", "Fr. S. Antarctic Lands", "Timor-Leste", "South Africa", "Lesotho", "Mexico", "Uruguay", "Brazil", "Bolivia", "Peru", "Colombia", "Panama", "Costa Rica", "Nicaragua", "Honduras", "El Salvador", "Guatemala", "Belize", "Venezuela", "Guyana", "Suriname", "France", "Ecuador", "Puerto Rico", "Jamaica", "Cuba", "Zimbabwe", "Botswana", "Namibia", "Senegal", "Mali", "Mauritania", "Benin", "Niger", "Nigeria", "Cameroon", "Togo", "Ghana", "Côte d'Ivoire", "Guinea", "Guinea-Bissau", "Liberia", "Sierra Leone", "Burkina Faso", "Central African Rep.", "Congo", "Gabon", "Eq. Guinea", "Zambia", "Malawi", "Mozambique", "eSwatini", "Angola", "Burundi", "Israel", "Lebanon", "Madagascar", "Palestine", "Gambia", "Tunisia", "Algeria", "Jordan", "United Arab Emirates", "Qatar", "Kuwait", "Iraq", "Oman", "Vanuatu", "Cambodia", "Thailand", "Laos", "Myanmar", "Vietnam", "North Korea", "South Korea", "Mongolia", "India", "Bangladesh", "Bhutan", "Nepal", "Pakistan", "Afghanistan", "Tajikistan", "Kyrgyzstan", "Turkmenistan", "Iran", "Syria", "Armenia", "Sweden", "Belarus", "Ukraine", "Poland", "Austria", "Hungary", "Moldova", "Romania", "Lithuania", "Latvia", "Estonia", "Germany", "Bulgaria", "Greece", "Turkey", "Albania", "Croatia", "Switzerland", "Luxembourg", "Belgium", "Netherlands", "Portugal", "Spain", "Ireland", "New Caledonia", "Solomon Is.", "New Zealand", "Australia", "Sri Lanka", "China", "Taiwan", "Italy", "Denmark", "United Kingdom", "Iceland", "Azerbaijan", "Georgia", "Philippines", "Malaysia", "Brunei", "Slovenia", "Finland", "Slovakia", "Czechia", "Eritrea", "Japan", "Paraguay", "Yemen", "Saudi Arabia", "Antarctica", "N. Cyprus", "Cyprus", "Morocco", "Egypt", "Libya", "Ethiopia", "Djibouti", "Somaliland", "Uganda", "Rwanda", "Bosnia and Herz.", "Macedonia", "Serbia", "Montenegro", "Kosovo", "Trinidad and Tobago", "S. Sudan" ]

missing_from_map = []

def compare_lists():
    for country in covidlist:
        if country not in maplist:
            missing_from_map.append(country)
    print(missing_from_map)

compare_lists()